# Generated by Django 4.1.7 on 2023-03-06 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_post_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_date',
        ),
        migrations.AddField(
            model_name='post',
            name='event_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
